#blog title
title: Yorita's blog
#email address
email: #your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  donate  
  XP XPz8faFqRvLhcHQEEnq5Hd9UGQmtNmmQFA  
baseurl: ""
url: "https://YoritaXP.github.io"
twitter_username: YoritaXP
github_username: YoritaXP

minima:
  date_format: "%Y/%m/%d %H:%M"

# Build settings
markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
theme: minima

plugins:
 - jekyll-feed

exclude:
 - Gemfile
 - Gemfile.lock

future: true