#blog title
title: Yorita's blog
#email address
email: yorita.crypto@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Yoritaのプログラミングメモ
baseurl: ""
url: "https://YoritaXP.github.io"
twitter_username: Yorita_P
github_username: YoritaP
google_analytics: UA-115625516-1

minima:
  date_format: "%Y/%m/%d %H:%M"

# Build settings
markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md
theme: minima

plugins:
 - jekyll-feed
 - nokogiri
exclude:
 - Gemfile
 - Gemfile.lock

future: true